#!/bin/bash

# This script is used when things has gotten messy and we need to return to the default open drivers

# Log file for traceback
MAX_SIZE_KB=5120
LOG_SIZE_KB=0
LOG_FILE=/var/log/ddm.log
LOG_FILE2=/var/log/ddm.log.1
if [ -f $LOG_FILE ]; then
  LOG_SIZE_KB=$(ls -s $LOG_FILE | awk '{print $1}')
  if [ $LOG_SIZE_KB -gt $MAX_SIZE_KB ]; then
    mv -f $LOG_FILE $LOG_FILE2
  fi
fi

# If not running in terminal, use GUI frontend
if [ ! -t 1 ]; then
  export DEBIAN_FRONTEND=gnome
fi

# Start the log
echo "===================================" | tee -a $LOG_FILE
echo "Running the script install-open" | tee -a $LOG_FILE
echo "Start at (m/d/y):" $(date +"%m/%d/%Y %H:%M:%S") | tee -a $LOG_FILE
echo "===================================" | tee -a $LOG_FILE

function purge_proprietary_drivers {
  rm /etc/X11/xorg.conf 2>/dev/null
  rm /etc/modprobe.d/nvidia* 2>/dev/null
  rm /etc/modprobe.d/blacklist-nouveau.conf 2>/dev/null
  # Leave nvidia-detect and nvidia-installer-cleanup
  apt-get purge -y --force-yes $(apt-show-versions | grep nvidia | grep -v detect | grep -v cleanup | cut -d':' -f1) 2>&1 | tee -a $LOG_FILE
  apt-get purge -y --force-yes $(apt-show-versions | grep fglrx | cut -d':' -f1) 2>&1 | tee -a $LOG_FILE
  apt-get purge -y --force-yes bumblebee* primus* primus*:i386 2>&1 | tee -a $LOG_FILE
  
  echo "Propietary drivers removed" | tee -a $LOG_FILE
}

function install_open {
  # Make sure you have the most used drivers installed 
  # These are installed by default on SolydXK
  DRIVER="xserver-xorg-video-nouveau xserver-xorg-video-vesa xserver-xorg-video-intel xserver-xorg-video-fbdev xserver-xorg-video-radeon xserver-xorg-video-ati xserver-xorg-video-nouveau"
  
  # Install the packages
  apt-get update
  echo "Frontend: $(echo $DEBIAN_FRONTEND)" | tee -a $LOG_FILE
  apt-get install --reinstall -y --force-yes $DRIVER 2>&1 | tee -a $LOG_FILE
  
  echo "Open drivers installed" | tee -a $LOG_FILE
  
  # Now cleanup
  purge_proprietary_drivers
}

# Install the open drivers
install_open
